project:
  type: website

website:
  title: "IS415-GAA-Project"
  navbar:
    left:
    - text: "Project Outline"
      href: "Project_Outline.html"
    - text: "Research Paper"
      href: "Research_Paper.html"
    - text: "Rshiny Application"
      href: "https://junhaoteo.shinyapps.io/is415_gaa_Hospital_Playlist/"
    - text: "Poster"
      href: "Poster.html"

    right: 
      - href: index.qmd
        text: Home
      - icon: github
      - href: about.qmd

format:
  html:
    theme: [Sandstone, style.scss]

editor: visual

