---
title: "Geographical Weighted Regression on Seoul's financial crimes"
---

# [*Project Motivation*]{.underline}

Financial crimes around the world have been on the rise.
In particular, Seoul has maintained its [crime rates](https://www-statista-com.libproxy.smu.edu.sg/statistics/1249396/south-korea-crime-rate-by-region/?locale=en) to be relatively consistent with its other regions despite having the [highest population density](https://www-statista-com.libproxy.smu.edu.sg/statistics/1112322/south-korea-population-density-by-province/) in South Korea.
One possible reason could be because the [number of police officers](https://www-statista-com.libproxy.smu.edu.sg/statistics/1290877/south-korea-number-of-police-officers-in-seoul/) in Seoul have been increasing.
In 2011, there were approximately 24990 police officers and by 2016, the number of police officers amounted to 27350.
However, this is just an assumption, which is why to test this assumption, it brings us to our project objective.

# [*Projects Objective*]{.underline}

The objective of this project is to allow the end-user to use our model in assessing what are the key factors that influence financial crimes and how much these factors explain the high/low financial crime rates in the country of their choice.
The results of this model will hopefully provide insights on how to reduce the occurrence of financial crimes to the user.
By using Seoul, we hope to showcase how our app operates and what kind of insights we can get by applying our model to a selected country.

# [*Data*]{.underline}

1.  Seoul's crime occurrence
2.  Economically inactive population by County
3.  Police post locations
4.  Bankruptcy rates
5.  Unemployment rates
6.  Population Density

# [*Story Board*]{.underline}

# [*Timeline*]{.underline}

# [*References*]{.underline}
